import type { IncomingMessage } from 'node:http';
import type { AgentHandler } from './agent';

export type ChannelStatus = 'disconnected' | 'connecting' | 'connected' | 'error';

export type AuthState =
    | 'needs_scan'
    | 'waiting_scan'
    | 'authenticated'
    | 'expired'
    | 'not_configured';

export type DmPolicy = 'pairing' | 'allowlist' | 'open' | 'disabled';

export type GroupPolicy = 'allowlist' | 'open' | 'disabled';

export type GroupActivation = 'mention' | 'always';

export type MediaType = 'image' | 'video' | 'audio' | 'document' | 'sticker';

/**
 * Interactive message capability flags.
 * Each channel declares which of these it supports.
 */
export type InteractiveCapability =
    | 'buttons'       // inline keyboard / action-row buttons
    | 'select'        // dropdown select menus
    | 'cards'         // rich card embeds
    | 'components'    // generic composite UIs (Discord components v2, etc.)
    | 'polls'         // native aggregated-voting polls
    | 'reactions'     // emoji reactions on a specific message (⏳/✅/❌ task presence)
    | 'typing'        // "X is typing..." ephemeral indicator
    | 'edit-message'; // edit an already-sent message body in place

/** Button style for interactive messages. */
export type ButtonStyle = 'primary' | 'secondary' | 'success' | 'danger';

export interface InteractiveButton {
    readonly label: string;
    readonly value: string;
    readonly style?: ButtonStyle;
}

export interface InteractiveOption {
    readonly label: string;
    readonly value: string;
}

export interface InteractiveTextBlock {
    readonly type: 'text';
    readonly text: string;
}

export interface InteractiveButtonsBlock {
    readonly type: 'buttons';
    readonly buttons: InteractiveButton[];
}

export interface InteractiveSelectBlock {
    readonly type: 'select';
    readonly placeholder?: string;
    readonly options: InteractiveOption[];
    readonly multiSelect?: boolean;
}

/**
 * Native poll — Telegram `sendPoll`, Discord `poll` field, Slack poll
 * block-kit. Different semantic from `buttons`: polls aggregate votes
 * across multiple participants and typically live in group chats.
 * Channels without native poll support (iMessage, Signal, WhatsApp)
 * render as a text fallback with numbered options.
 */
export interface InteractivePollBlock {
    readonly type: 'poll';
    readonly question: string;
    readonly options: string[];
    /** Whether voter identities are hidden (Telegram default true). */
    readonly anonymous?: boolean;
    /** Whether a voter can pick more than one option. */
    readonly allowMultiple?: boolean;
}

export type InteractiveBlock =
    | InteractiveTextBlock
    | InteractiveButtonsBlock
    | InteractiveSelectBlock
    | InteractivePollBlock;

export interface InteractiveReply {
    readonly blocks: InteractiveBlock[];
}

export interface InteractionCallback {
    readonly type: 'button_click' | 'select_choice';
    readonly value: string;
    readonly messageId: string;
    readonly peer: Peer;
    readonly sender?: { id: string; name?: string };
}

export interface Peer {
    id: string;
    type: 'user' | 'group' | 'channel';
    name?: string;
}

export interface Media {
    type: MediaType;
    url?: string;
    mimeType?: string;
    fileName?: string;
    fileSize?: number;
    caption?: string;
    data?: string;
}

export interface Message {
    id: string;
    channelName: string;
    peer: Peer;
    sender?: { id: string; name?: string };
    body: string;
    /**
     * True when body was generated by the channel adapter (e.g. "[Image]",
     * "[Video]"), not typed by the user. Used by the coalesce layer to
     * suppress placeholder text when a real caption arrives in the same window.
     */
    synthetic?: boolean;
    timestamp: string;
    replyTo?: { id: string; body?: string; sender?: string };
    media?: Media[];
}

export interface OutboundMessage {
    peer: Peer;
    body?: string;
    replyTo?: string;
    media?: Media[];
    interactive?: InteractiveReply;
}

export interface ReactionOptions {
    messageId: string;
    peer: Peer;
    emoji: string;
    remove?: boolean;
}

export interface PairingRequest {
    channelName: string;
    senderId: string;
    senderName?: string;
    messagePreview?: string;
    timestamp: number;
}

export type PairingRequestHandler = (request: PairingRequest) => void;

export interface ChannelEvents {
    onMessage: (message: Message) => Promise<void>;
    onInteraction: (callback: InteractionCallback) => Promise<void>;
    onStatusChange: (status: ChannelStatus) => void;
    onError: (error: Error) => void;
    onQR: (qrData: string) => void;
    onAuthUpdate: (status: AuthState) => void;
}

export interface AccessControlUpdate {
    dmPolicy?: DmPolicy;
    allowFrom?: string[];
    blockedFrom?: string[];
    groupPolicy?: GroupPolicy;
    allowedGroups?: string[];
}

export type AuthType = 'qr' | 'token' | 'oauth' | 'none';

export interface StreamingCapability {
    readonly editBased: boolean;
    readonly minEditIntervalMs: number;
}

export interface Channel {
    readonly name: string;
    readonly status: ChannelStatus;
    readonly enabled: boolean;
    readonly dmPolicy: DmPolicy;
    readonly groupPolicy: GroupPolicy;
    readonly authType: AuthType;
    readonly streaming?: StreamingCapability;
    readonly capabilities?: readonly InteractiveCapability[];

    connect(): Promise<void>;
    disconnect(): Promise<void>;

    send(message: OutboundMessage): Promise<string>;
    sendTyping(peer: Peer): Promise<void>;
    react(options: ReactionOptions): Promise<void>;

    /**
     * Optional native poll. Channels that implement it (Telegram, Discord)
     * deliver the platform's native poll UI. Channels that don't can fall
     * back to a text rendering via `send()` — the router resolves that,
     * so leaving `sendPoll` undefined is valid.
     */
    sendPoll?(args: {
        peer: Peer;
        question: string;
        options: readonly string[];
        anonymous?: boolean;
        allowMultiple?: boolean;
        durationHours?: number;
    }): Promise<string>;

    clearSession?(): Promise<void>;
    editMessage?(messageId: string, peer: Peer, body: string): Promise<void>;
    updateAccessControl?(update: AccessControlUpdate): void;
    pairingRequestHandler?: PairingRequestHandler | null;

    on<K extends keyof ChannelEvents>(event: K, handler: ChannelEvents[K]): void;
    off<K extends keyof ChannelEvents>(event: K, handler: ChannelEvents[K]): void;
}

export interface WebhookChannel {
    readonly webhookPath: string;
    verifyWebhook(req: IncomingMessage, body: string): boolean;
    extractEvents(parsed: unknown): unknown[];
    handleWebhookEvent(event: unknown): Promise<void>;
}

export function isWebhookChannel(ch: Channel): ch is Channel & WebhookChannel {
    return 'webhookPath' in ch && 'handleWebhookEvent' in ch && 'verifyWebhook' in ch;
}

export interface BaseChannelConfig {
    enabled: boolean;
    dmPolicy: DmPolicy;
    groupPolicy?: GroupPolicy;
    allowFrom?: string[];
    blockedFrom?: string[];
    allowedGroups?: string[];
}

export interface ChannelWorkerConfig {
    readonly channel: Channel;
    readonly threadId: string;
    readonly agentHandler: AgentHandler;
    readonly onReply: (
        text: string,
        peer: Peer,
        replyTo?: string,
        options?: {
            readonly buttons?: ReadonlyArray<InteractiveButton>;
            readonly media?: ReadonlyArray<Media>;
        },
    ) => Promise<void>;
    readonly onSendPoll: (
        peer: Peer,
        question: string,
        options: readonly string[],
        pollOptions?: {
            readonly anonymous?: boolean;
            readonly allowMultiple?: boolean;
            readonly durationHours?: number;
        },
    ) => Promise<void>;
    readonly coalesceDelayMs?: number;
    readonly agentTimeoutMs?: number;
    readonly backgroundTurnTimeoutMs?: number;
    /**
     * Lazy closure that returns a user-safe snapshot of gateway-wide state
     * (channel connection flags, uptime, active thread count). Used by the
     * `/status` slash command. Returns undefined when the gateway wasn't
     * constructed with a snapshot provider (unit tests, legacy callers).
     */
    readonly getGatewayStatus?: () => GatewayStatusSnapshot | undefined;
}

/**
 * Channel + uptime + thread counts surfaced to user-facing commands. No
 * tokens, no peer ids, no URLs — adding fields here is a conscious privacy
 * choice. Everything is kept to bare counts + booleans so the payload
 * remains safe to render inside a chat reply.
 */
export interface GatewayStatusSnapshot {
    readonly uptimeMs: number;
    readonly channels: ReadonlyArray<{
        readonly name: string;
        readonly status: ChannelStatus;
        readonly enabled: boolean;
    }>;
    readonly activeThreads: number;
    /** Gateway WS port. `host` is deliberately omitted (leaks deployment). */
    readonly port?: number;
    /** Build identity — git short-sha when available, `dev` otherwise. */
    readonly version?: string;
    /** Inbound webhook server state; undefined when webhook support is off. */
    readonly webhook?: {
        readonly enabled: boolean;
        readonly port?: number;
        /** Count of registered route prefixes (we do not leak the paths). */
        readonly routeCount: number;
    };
    /** Proactive engine state; undefined when proactive support is off. */
    readonly proactive?: {
        readonly running: boolean;
        readonly heartbeats: number;
        readonly cronJobs: number;
        readonly inboundWebhooks: number;
        /** Wall-clock ms when the last heartbeat fired; undefined if never. */
        readonly lastHeartbeatAt?: number;
    };
}
